// Power Query (M) - cole no Editor Avançado do Power Query no Power BI
// Ajuste o caminho do arquivo em File.Contents se necessário.
let
    Fonte = Csv.Document(File.Contents("PATH/TO/your_project/data/repos_concatenated.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    PromotedHeaders = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
    RenomearColunas = Table.RenameColumns(PromotedHeaders,{
        {"full_name","full_name"},{"name","name"},{"owner","owner"},{"language","language"},
        {"stars","stars"},{"forks","forks"},{"open_issues","open_issues"},{"watchers","watchers"},
        {"created_at","created_at"},{"updated_at","updated_at"},{"license","license"},
        {"topics","topics"},{"url","url"},{"description","description"}
    }),
    AlterarTipos = Table.TransformColumnTypes(RenomearColunas,{
        {"full_name", type text}, {"name", type text}, {"owner", type text}, {"language", type text},
        {"stars", Int64.Type}, {"forks", Int64.Type}, {"open_issues", Int64.Type}, {"watchers", Int64.Type},
        {"created_at", type datetime}, {"updated_at", type datetime}, {"license", type text},
        {"topics", type text}, {"url", type text}, {"description", type text}
    }),
    SubstituirNulosTexto = Table.ReplaceValue(AlterarTipos,null,"Desconhecido",Replacer.ReplaceValue,{"language","license","topics","description"}),
    AdicionarYearMonth = Table.AddColumn(SubstituirNulosTexto, "YearMonth", each Date.ToText(Date.From([created_at]), "yyyy-MM"), type text),
    AdicionarStarsLog = Table.AddColumn(AdicionarYearMonth, "StarsLog", each if [stars] = null then null else Number.Log10(Number.From([stars]) + 1), type number),
    Ordenar = Table.Sort(AdicionarStarsLog,{{"stars", Order.Descending}})
in
    Ordenar